import "./globals.css";
import "../styles/fonts.css";
import "../styles/main.css";
import type { Metadata } from "next";
import localFont from "@next/font/local";
import { Inter } from "next/font/google";
import NavBar from "@/components/common/navbar";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { GeneralContextProvider } from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const kanitBold = localFont({
  src: [
    {
      path: "../public/assets/fonts/Kanit-Bold.ttf",
    },
  ],
  variable: "--kanit-bold",
});
const kanitBolder = localFont({
  src: [
    {
      path: "../public/assets/fonts/Kanit-ExtraBold.ttf",
    },
  ],
  variable: "--kanit-bolder",
});
const kanitThin = localFont({
  src: [
    {
      path: "../public/assets/fonts/Kanit-Thin.ttf",
    },
  ],
  variable: "--kanit-thin",
});
const kanit = localFont({
  src: [
    {
      path: "../public/assets/fonts/Kanit-Regular.ttf",
    },
  ],
  variable: "--kanit-regular",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${kanitBold.variable} ${kanitBolder.variable} ${kanitThin.variable} ${kanit.variable}`}
    >
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <GeneralContextProvider>
          <main className="flex flex-col font-normal">
            <NavBar />
            {children}
            {/* <Home /> */}
            <Toaster />
          </main>
          </GeneralContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
